### ISSUE TITLE
testing: release 30.20191002.0

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-streams#19]
First, verify that you meet all the [prerequisites](https://github.com/coreos/fedora-coreos-streams/blob/master/release-prereqs.md)

# Pre-release

## Promote testing-devel changes

From the checkout for `fedora-coreos-config` (replace `upstream` below with
whichever remote name tracks `coreos/`):

- [x] `git fetch upstream`
- [x] `git checkout testing`
- [x] `git reset --hard upstream/testing`
- [x] `/path/to/fedora-coreos-releng-automation/scripts/promote-config.sh testing-devel`
- [x] Sanity check promotion with `git show`
- [x] Open PR against the `testing` branch on https://github.com/coreos/fedora-coreos-config
- [x] Ideally have at least one other person check it and approve before merging

## Build

- [x] Start a [pipeline build](https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/build?delay=0sec) (select `testing`, and fill in version number using the `N.YYYYMMDD.P` format, pending finalization of https://github.com/coreos/fedora-coreos-tracker/issues/81)
- [x] Wait for the job to finish

## Sanity-check the build

Using the [the build browser](https://builds.coreos.fedoraproject.org/browser) for the `testing` stream:

- [x] Verify that the parent commit and version match the previous `testing` release (in the future, we'll want to integrate this check in the release job)
- [x] Run kola on AMI to sanity check it (this will be run automatically on all builds in the future):

```
kola -p aws run --aws-ami <ami-id> --aws-region us-east-1 --parallel 10 -b fcos
```

## Sign the CHECKSUMS file for releng

This is a stopgap until we do signing through fedora-messaging.

- [x] Download the `CHECKSUMS` file locally:

```
aws s3 cp s3://fcos-builds/prod/streams/testing/builds/$VERSION/CHECKSUMS .
```

- [x] **Confirm that the SHA256 of the `CHECKSUMS` file you just downloaded matches the one from the pipeline Jenkins log output**
- [x] Sign it with your key: `gpg2 --output CHECKSUMS.sig --detach-sign CHECKSUMS`
- [x] Push your signature to the bucket:

```
aws s3 cp --acl=public-read CHECKSUMS.sig s3://fcos-builds/prod/streams/testing/builds/$VERSION/CHECKSUMS.sig
```

# ⚠️ Release ⚠️

IMPORTANT: this is the point of no return here. Once the OSTree commit is
imported into the unified repo, any machine that manually runs `rpm-ostree
upgrade` will have the new update.

## Signing artifacts and importing OSTree commit

In the future, the signing part will be integrated in the build job and the OSTree commit import will be integrated in the release job.

- [x] Open an issue on https://pagure.io/releng similar to https://pagure.io/releng/issue/8578 to ask for the artifacts to be signed and OSTree commit to be imported
- [x] Wait for releng to process the request
- [x] Verify that the image artifact signatures are present and have the right ACL, e.g.:

```
aws s3 ls --recursive s3://fcos-builds/prod/streams/testing/builds/$VERSION/
curl -I https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/$VERSION/x86_64/fedora-coreos-$VERSION-qemu.qcow2.xz.sig
```

- [x] Verify that the OSTree commit and its signature are present and valid by booting a VM at the previous release (e.g. `cosa run -d /path/to/previous.qcow2`) and verifying that `rpm-ostree upgrade` works and `rpm-ostree status` shows a valid signature.

## Run the release job

- [x] Run the [release job](https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/build?delay=0sec), filling in for parameters `testing` and the new version ID
- [x] Wait for job to finish

At this point, Cincinnati will see the new release on its next refresh and create a corresponding node in the graph without edges pointing to it yet.

## Refresh metadata (stream and updates)

From a checkout of this repo:

- [x] Update stream metadata, by running:

```
fedora-coreos-stream-generator -releases=https://fcos-builds.s3.amazonaws.com/prod/streams/testing/releases.json  -output-file=streams/testing.json -pretty-print
```

- [x] Update updates metadata, editing `updates/testing.json` and replacing the oldest rollout with your new one:
  - [x] Set `version` field to the new version
  - [x] Set `start_epoch` field to a future timestamp for the rollout start (e.g. `date -d '2019/09/10 14:30UTC' +%s`)
  - [x] Set `start_percentage` field to `0.0`
  - [x] Set `duration_minutes` field to a reasonable rollout window (e.g. `2880` for 48h)
  - [x] Update the `last-modified` field to current time (e.g. `date -u +%Y-%m-%dT%H:%M:%SZ`)

A reviewer can validate the `start_epoch` time by running `date -u -d @<EPOCH>`. An example of encoding and decoding in one step: `date -d '2019/09/10 14:30UTC' +%s | xargs -I{} date -u -d @{}`. 

- [x] Commit the changes and open a PR against the repo.
- [x] Wait for the PR to be approved.
- [x] Once approved, merge it and push the content to S3:

```
aws s3 cp --acl public-read --cache-control 'max-age=60' streams/testing.json s3://fcos-builds/streams/testing.json

aws s3 cp --acl public-read --cache-control 'max-age=60' updates/testing.json s3://fcos-builds/updates/testing.json
```

- [x] Verify the new version shows up on [the download page](https://getfedora.org/en/coreos/download/)
- [x] Verify the incoming edges are showing up in the update graph:

```
curl -H 'Accept: application/json' 'https://updates.coreos.stg.fedoraproject.org/v1/graph?basearch=x86_64&stream=testing&rollout_wariness=0'
```

NOTE: In the future, most of these steps will be automated and a syncer will push the updated metadata to S3.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/188

**Comment by jlebon** [comment]
https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/9012/console

**Comment by jlebon** [comment]
https://pagure.io/releng/issue/8864

**Comment by jlebon** [comment]
https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/147/console

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-streams/pull/21

**Comment by lucab** [comment]
My canary node did successfully upgrade at around `Fri Oct  4 06:44:48 UTC 2019`.

**Comment by dustymabe** [comment]
Mine did too. I think we can close this issue!

**Comment by dustymabe** [comment]
Thanks for doing the release @jlebon
