### ISSUE TITLE
testing: release 30.20191014.0

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-streams#23]
First, verify that you meet all the [prerequisites](https://github.com/coreos/fedora-coreos-streams/blob/master/release-prereqs.md)

# Pre-release

## Promote testing-devel changes

From the checkout for `fedora-coreos-config` (replace `upstream` below with
whichever remote name tracks `coreos/`):

- [x] `git fetch upstream`
- [x] `git checkout testing`
- [x] `git reset --hard upstream/testing`
- [x] `/path/to/fedora-coreos-releng-automation/scripts/promote-config.sh testing-devel`
- [x] Sanity check promotion with `git show`
- [x] Open PR against the `testing` branch on https://github.com/coreos/fedora-coreos-config
- [x] Post a link to the PR as a comment to this issue
- [x] Ideally have at least one other person check it and approve
- [x] Once CI has passed, merge it

## Build

- [x] Start a [pipeline build](https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/build?delay=0sec) (select `testing`, and fill in version number using the `N.YYYYMMDD.P` format, pending finalization of https://github.com/coreos/fedora-coreos-tracker/issues/81)
- [x] Post a link to the job as a comment to this issue
- [x] Wait for the job to finish

## Sanity-check the build

Using the [the build browser](https://builds.coreos.fedoraproject.org/browser) for the `testing` stream:

- [x] Verify that the parent commit and version match the previous `testing` release (in the future, we'll want to integrate this check in the release job)
- [x] Check [kola AWS run](https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-kola-aws) to make sure it didn't fail

# ⚠️ Release ⚠️

IMPORTANT: this is the point of no return here. Once the OSTree commit is
imported into the unified repo, any machine that manually runs `rpm-ostree
upgrade` will have the new update.

## Importing OSTree commit

In the future, the OSTree commit import will be integrated in the release job.

- [x] Open an issue on https://pagure.io/releng to ask for the OSTree commit to be imported (include a URL to the .sig which should be alongside the tarfile in the bucket and signed by the primary Fedora key)
- [x] Post a link to the issue as a comment in this issue
- [x] Wait for releng to process the request
- [x] Verify that the OSTree commit and its signature are present and valid by booting a VM at the previous release (e.g. `cosa run -d /path/to/previous.qcow2`) and verifying that `rpm-ostree upgrade` works and `rpm-ostree status` shows a valid signature.

## Run the release job

- [x] Run the [release job](https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/build?delay=0sec), filling in for parameters `testing` and the new version ID
- [x] Post a link to the job as a comment to this issue
- [x] Wait for job to finish

At this point, Cincinnati will see the new release on its next refresh and create a corresponding node in the graph without edges pointing to it yet.

## Refresh metadata (stream and updates)

From a checkout of this repo:

- [x] Update stream metadata, by running:

```
fedora-coreos-stream-generator -releases=https://fcos-builds.s3.amazonaws.com/prod/streams/testing/releases.json  -output-file=streams/testing.json -pretty-print
```

- [x] Update updates metadata, editing `updates/testing.json` and replacing the oldest rollout with your new one:
  - [x] Set `version` field to the new version
  - [x] Set `start_epoch` field to a future timestamp for the rollout start (e.g. `date -d '2019/09/10 14:30UTC' +%s`)
  - [x] Set `start_percentage` field to `0.0`
  - [x] Set `duration_minutes` field to a reasonable rollout window (e.g. `2880` for 48h)
  - [x] Update the `last-modified` field to current time (e.g. `date -u +%Y-%m-%dT%H:%M:%SZ`)

A reviewer can validate the `start_epoch` time by running `date -u -d @<EPOCH>`. An example of encoding and decoding in one step: `date -d '2019/09/10 14:30UTC' +%s | xargs -I{} date -u -d @{}`. 

- [x] Commit the changes and open a PR against the repo.
- [x] Post a link to the PR as a comment to this issue
- [x] Wait for the PR to be approved.
- [x] Once approved, merge it and push the content to S3:

```
aws s3 sync --acl public-read --cache-control 'max-age=60' --exclude '*' --include 'streams/*' --include 'updates/*' . s3://fcos-builds
```

- [x] Verify the new version shows up on [the download page](https://getfedora.org/en/coreos/download/)
- [x] Verify the incoming edges are showing up in the update graph:

```
curl -H 'Accept: application/json' 'https://updates.coreos.stg.fedoraproject.org/v1/graph?basearch=x86_64&stream=testing&rollout_wariness=0'
```

NOTE: In the future, most of these steps will be automated and a syncer will push the updated metadata to S3.

**Comment by bgilbert** [comment]
https://github.com/coreos/fedora-coreos-config/pull/198

**Comment by bgilbert** [comment]
https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/9614/

**Comment by bgilbert** [comment]
The [kola AWS run](https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-kola-aws/62/console) is failing to schedule.

**Comment by jlebon** [comment]
Ahh yup, should be fixed by: https://github.com/coreos/fedora-coreos-pipeline/pull/149.

**Comment by jlebon** [comment]
With that patch merged, you should be able to just stop that kola AWS job and launch a new one.

**Comment by bgilbert** [comment]
https://pagure.io/releng/issue/8907

**Comment by bgilbert** [comment]
https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/158/

**Comment by bgilbert** [comment]
https://github.com/coreos/fedora-coreos-streams/pull/24

**Comment by bgilbert** [comment]
Rollout started, perhaps 30-45 minutes after the scheduled start time.

**Comment by bgilbert** [comment]
The rollout should technically be done by now, but I'm pretty consistently getting gateway timeouts from Cincinnati.

**Comment by bgilbert** [comment]
Optimistically closing this out.

**Comment by lucab** [comment]
My canary did correctly update at around `Fri Oct 18 17:43:27 UTC 2019`.

**Comment by dustymabe** [comment]
Mine finally updated at `Fri Oct 18 17:43`
