### ISSUE TITLE
stable: new release on 2021-09-06 (34.20210821.3.0)

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-streams#362]
First, verify that you meet all the [prerequisites](https://github.com/coreos/fedora-coreos-streams/blob/main/release-prereqs.md)

Name this issue `stable: new release on YYYY-MM-DD` with today's date. Once the pipeline spits out the new version ID, you can append it to the title e.g. `(31.20191117.3.0)`.

# Pre-release

## Promote testing changes to stable

- [x] Add the `ok-to-promote` label to the issue
- [x] Review the promotion PR opened by the bot against the `stable` branch on https://github.com/coreos/fedora-coreos-config
- [x] Once CI has passed, merge it

## Build

- [x] Start a [pipeline build](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/build?delay=0sec) (select `stable`, leave all other defaults)
- [x] Post a link to the job as a comment to this issue
- [x] Wait for the job to finish

## Sanity-check the build

Using the [the build browser for the `stable` stream](https://builds.coreos.fedoraproject.org/browser?stream=stable):

- [x] Verify that the parent commit and version match the previous `stable` release (in the future, we'll want to integrate this check in the release job)
- [ ] Check [kola AWS run](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-aws/) to make sure it didn't fail
- [x] Check [kola GCP run](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-gcp/) to make sure it didn't fail
- [ ] Check [kola OpenStack run](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-openstack/) to make sure it didn't fail

# ⚠️ Release ⚠️

IMPORTANT: this is the point of no return here. Once the OSTree commit is
imported into the unified repo, any machine that manually runs `rpm-ostree
upgrade` will have the new update.

## Run the release job

- [x] Run the [release job](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/build?delay=0sec), filling in for parameters `stable` and the new version ID
- [x] Post a link to the job as a comment to this issue
- [x] Wait for job to finish
- [x] Verify that the OSTree commit and its signature are present and valid by booting a VM at the previous release (e.g. `cosa run --qemu-image /path/to/previous.qcow2`) and verifying that `rpm-ostree upgrade --bypass-driver` works and `rpm-ostree status` shows a valid signature.

At this point, Cincinnati will see the new release on its next refresh and create a corresponding node in the graph without edges pointing to it yet.

## Refresh metadata (stream and updates)

From a checkout of this repo:

- [x] Update stream metadata, by running:

```
fedora-coreos-stream-generator -releases=https://fcos-builds.s3.amazonaws.com/prod/streams/stable/releases.json  -output-file=streams/stable.json -pretty-print
```

- [x] Add a rollout.  For a 48-hour rollout starting at 10 AM ET, run:

```
./rollout.py add stable <version> "10 am ET" 48
```

- [x] Commit the changes and open a PR against the repo.  Paste the output of `make print-rollouts` into the PR description.
- [x] Post a link to the PR as a comment to this issue
- [x] Wait for the PR to be approved.
- [x] Once approved, merge it and verify that the [`sync-stream-metadata` job](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/sync-stream-metadata/) syncs the contents to S3
- [x] Verify the new version shows up on [the download page](https://getfedora.org/en/coreos/download/)
- [x] Verify the incoming edges are showing up in the [update graph](https://builds.coreos.fedoraproject.org/graph?stream=stable)

<details>
  <summary>Update graph manual check</summary>

```
curl -H 'Accept: application/json' 'https://updates.coreos.fedoraproject.org/v1/graph?basearch=x86_64&stream=stable&rollout_wariness=0'
```

</details>

NOTE: In the future, most of these steps will be automated.

## Housekeeping

- [x] If one doesn't already exist, [open an issue](https://github.com/coreos/fedora-coreos-streams/issues/new?labels=kind/release,jira&template=stable.md) in this repo with the approximate date in the title of the next release in this stream.
- [x] Issues opened via the previous link will automatically create a linked Jira card. Assign the GitHub issue and Jira card to the next person in the [rotation](https://hackmd.io/WCA8XqAoRvafnja01JG_YA).

**Comment by sinnykumari** [comment]
Promotion PR - https://github.com/coreos/fedora-coreos-config/pull/1203

**Comment by sinnykumari** [comment]
pipeline build - https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/2607/

**Comment by sinnykumari** [comment]
[kola openstack](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-openstack/337/console) test for x86_64 failed. Unique failures:
```
14:44:48  === RUN   rpmostree.upgrade-rollback/upgrade
14:45:06  --- FAIL: podman.base (310.86s)
14:45:06          harness.go:1124: Cluster failed starting machines: waiting for instance to run: time limit exceeded
...
14:56:38  === RUN   rpmostree.install-uninstall/install
14:57:16  --- FAIL: coreos.auth.verify (308.60s)
14:57:16          harness.go:1124: Cluster failed starting machines: waiting for instance to run: time limit exceeded
...
```

**Comment by sinnykumari** [comment]
[kola aws](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-aws/560/console) test run for aarch64 failed:

```
...
13:53:30  Failed in branch run_upgrades
...

14:20:24  --- FAIL: podman.base (405.63s)
14:20:24      --- PASS: podman.base/info (3.00s)
14:20:24      --- FAIL: podman.base/resources (2.50s)
14:20:24              cluster.go:143: time="2021-09-07T12:14:19Z" level=error msg="Cannot get exit code: died not found: unable to find event"
14:20:24              podman.go:278: Failed to run "sudo podman run --net=none --rm --memory-reservation=10m echo echo 1": output: "1" status: "Process exited with status 127"
14:20:24  --- FAIL: rpmostree.status (394.95s)
14:20:24          harness.go:1124: Cluster failed starting machines: machine "i-036d533c908f644c9" failed basic checks: some systemd units failed:
14:20:24  multipathd.service
```

**Comment by dustymabe** [comment]
> [kola openstack](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-openstack/337/console) test for x86_64 failed. Unique failures:
> 
> ```
> 14:44:48  === RUN   rpmostree.upgrade-rollback/upgrade
> 14:45:06  --- FAIL: podman.base (310.86s)
> 14:45:06          harness.go:1124: Cluster failed starting machines: waiting for instance to run: time limit exceeded
> ...
> 14:56:38  === RUN   rpmostree.install-uninstall/install
> 14:57:16  --- FAIL: coreos.auth.verify (308.60s)
> 14:57:16          harness.go:1124: Cluster failed starting machines: waiting for instance to run: time limit exceeded
> ...
> ```

Yeah, we've been seeing this lately (see https://github.com/coreos/fedora-coreos-streams/issues/360#issuecomment-913968082). Possible workaround landed a little bit ago in https://github.com/coreos/coreos-assembler/pull/2416

**Comment by dustymabe** [comment]
> [kola aws](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-aws/560/console) test run for aarch64 failed:
> 
> ```
> ...
> 13:53:30  Failed in branch run_upgrades
> ...
> 
> 14:20:24  --- FAIL: podman.base (405.63s)
> 14:20:24      --- PASS: podman.base/info (3.00s)
> 14:20:24      --- FAIL: podman.base/resources (2.50s)
> 14:20:24              cluster.go:143: time="2021-09-07T12:14:19Z" level=error msg="Cannot get exit code: died not found: unable to find event"
> 14:20:24              podman.go:278: Failed to run "sudo podman run --net=none --rm --memory-reservation=10m echo echo 1": output: "1" status: "Process exited with status 127"
> 14:20:24  --- FAIL: rpmostree.status (394.95s)
> 14:20:24          harness.go:1124: Cluster failed starting machines: machine "i-036d533c908f644c9" failed basic checks: some systemd units failed:
> 14:20:24  multipathd.service
> ```

hmmm. not sure on the `podman.base/resources` one. the `multipathd.service` failure is something I've been seeing a lot of lately, though, and probably needs to be looked at. I'd say re-run the kola aws test and hopefully the `podman.base/resources` was just a flake. You'll probably see more of the `multipathd.service` failures though, but I'd say you can ignore those.

**Comment by sinnykumari** [comment]
> hmmm. not sure on the `podman.base/resources` one. the `multipathd.service` failure is something I've been seeing a lot of lately, though, and probably needs to be looked at. I'd say re-run the kola aws test and hopefully the `podman.base/resources` was just a flake. You'll probably see more of the `multipathd.service` failures though, but I'd say you can ignore those.

Started another kola-aws test run for aarch64 - https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-aws/561/

**Comment by sinnykumari** [comment]
> Started another kola-aws test run for aarch64 - https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-aws/561/

Test run looks better, failed this time due to failed upgrade test because this is the first release in the stream (no old aarch64 AMI to upgrade from) which is expected.

**Comment by sinnykumari** [comment]
Release job - https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/651/

**Comment by sinnykumari** [comment]
**x86_64:**
```
$ rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Tue 2021-09-07 15:55:13 UTC)
Deployments:
● fedora:fedora/x86_64/coreos/stable
                   Version: 34.20210821.3.0 (2021-09-07T09:49:44Z)
                    Commit: 540eed43f9a9cdbfb11d0b6fdb32ebaeb5e1af04dab7b99ceb240e179f614130
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39

  fedora:fedora/x86_64/coreos/stable
                   Version: 34.20210808.3.0 (2021-08-23T18:41:14Z)
                    Commit: 6b7e18634c32d15efd59b18c0fdc5c26d2e00dbd3afc16965509ba6f1c42c274
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
```

**aarch64:**
```$ rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Tue 2021-09-07 16:24:19 UTC)
Deployments:
● fedora:fedora/aarch64/coreos/stable
                   Version: 34.20210821.3.0 (2021-09-07T10:18:50Z)
                    Commit: 8b577dfe9c94b388218c561b9deda2707eb49293b6ae6c62365d32712b360f97
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39

  fedora:fedora/aarch64/coreos/next
                   Version: 34.20210904.1.0 (2021-09-07T00:44:19Z)
                    Commit: e3887a78116d0be82c39e18610b0f39a9b2606196bf6f1b4cb24a9c1f6c9cb29
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
```

**Comment by sinnykumari** [comment]
Release metadata update - https://github.com/coreos/fedora-coreos-streams/pull/366

**Comment by sinnykumari** [comment]
Incoming edges looks good for x86_64.

for aarch64, see https://github.com/coreos/fedora-coreos-streams/issues/360#issuecomment-914319666

**Comment by sinnykumari** [comment]
Issue for next release will be created once https://github.com/coreos/fedora-coreos-streams/pull/365 gets merged
