### ISSUE TITLE
testing: new release 35.20211029.2.0 on 2021-11-09

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-streams#405]
First, verify that you meet all the [prerequisites](https://github.com/coreos/fedora-coreos-streams/blob/main/RELEASE.md#prerequisites)

Name this issue `testing: new release on YYYY-MM-DD` with today's date. Once the pipeline spits out the new version ID, you can append it to the title e.g. `(31.20191117.2.0)`.

# Pre-release

## Promote ~testing-devel~ _next_ changes to testing

- ❌ ~Add the `ok-to-promote` label to the issue~
    - [x] promotion PR was opened manually because of https://github.com/coreos/fedora-coreos-streams/issues/405#issuecomment-961376506
- [x] Review the promotion PR opened by the bot against the `testing` branch on https://github.com/coreos/fedora-coreos-config
- [x] Once CI has passed, merge it

## Build

- [x] Start a [pipeline build](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/build?delay=0sec) (select `testing`, leave all other defaults). This will automatically run multi-arch builds.
- Post links to the jobs as a comment to this issue
    - [x] x86_64
    - [x] aarch64 ([multi-arch pipeline](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/multi-arch-pipeline/))
- Wait for the jobs to finish and succeed
    - [x] x86_64
    - [x] aarch64

## Sanity-check the build

Using the [the build browser for the `testing` stream](https://builds.coreos.fedoraproject.org/browser?stream=testing):

- Verify that the parent commit and version match the previous `testing` release (in the future, we'll want to integrate this check in the release job)
    - [x] x86_64
    - [x] aarch64
- Check [kola AWS runs](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-aws/) to make sure they didn't fail
    - [x] x86_64
    - [x] aarch64
- [x] Check [kola GCP run](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-gcp/) to make sure it didn't fail
- [x] Check [kola OpenStack run](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-openstack/) to make sure it didn't fail

# ⚠️ Release ⚠️

IMPORTANT: this is the point of no return here. Once the OSTree commit is
imported into the unified repo, any machine that manually runs `rpm-ostree
upgrade` will have the new update.

## Run the release job

- [x] Run the [release job](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/build?delay=0sec), filling in for parameters `testing` and the new version ID
- [x] Post a link to the job as a comment to this issue
- [x] Wait for job to finish

At this point, Cincinnati will see the new release on its next refresh and create a corresponding node in the graph without edges pointing to it yet.

## Refresh metadata (stream and updates)

**_NOTE: We can't use the automated workflow for this release because we need to add an update barrier.  The testing release should be handled as a separate fedora-coreos-streams PR, following these manual instructions:_**

- [x] Make sure your `fedora-coreos-stream-generator` binary is up-to-date.

From a checkout of this repo:

- [x] Update stream metadata, by running:

```
fedora-coreos-stream-generator -releases=https://fcos-builds.s3.amazonaws.com/prod/streams/testing/releases.json  -output-file=streams/testing.json -pretty-print
```

- [x] Add a rollout **_with a barrier_**.  For example, for a 48-hour rollout starting at 10 AM ET the same day, run:

```
./rollout.py add testing <version> "10 am ET today" 48 --barrier https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/
```

- [x] Commit the changes and open a PR against the repo
- [x] Post a link to the resulting PR as a comment to this issue
- [x] Wait for two people to review and approve the PR
- [x] Once approved, merge it and verify that the [`sync-stream-metadata` job](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/sync-stream-metadata/) syncs the contents to S3
- [x] Verify the new version shows up on [the download page](https://getfedora.org/en/coreos/download?stream=testing)
- Verify the incoming edges are showing up in the update graph.
    - [x] [x86_64](https://builds.coreos.fedoraproject.org/graph?stream=testing&basearch=x86_64)
    - [x] [aarch64](https://builds.coreos.fedoraproject.org/graph?stream=testing&basearch=aarch64)

<details>
  <summary>Update graph manual check</summary>

```
curl -H 'Accept: application/json' 'https://updates.coreos.fedoraproject.org/v1/graph?basearch=x86_64&stream=testing&rollout_wariness=0'
curl -H 'Accept: application/json' 'https://updates.coreos.fedoraproject.org/v1/graph?basearch=aarch64&stream=testing&rollout_wariness=0'
```

</details>

NOTE: In the future, most of these steps will be automated.

## Housekeeping

- [x] If one doesn't already exist, [open an issue](https://github.com/coreos/fedora-coreos-streams/issues/new?labels=kind/release,jira&template=testing.md) in this repo for the next release in this stream. Use the approximate date of the release in the title.
- [x] Issues opened via the previous link will automatically create a linked Jira card. Assign the GitHub issue and Jira card to the next person in the [rotation](https://hackmd.io/WCA8XqAoRvafnja01JG_YA).

**Comment by dustymabe** [comment]
adjusted the release target date to next tuesday since we're [re-orienting around the F35 release](https://github.com/coreos/fedora-coreos-tracker/blob/main/Design.md#major-fedora-version-rebases)

**Comment by dustymabe** [comment]
Note that per [docs](https://github.com/coreos/fedora-coreos-tracker/blob/main/Design.md#major-fedora-version-rebases) this will be a promotion from `next` to `testing`, not from `testing-devel` to `testing`.

**Comment by bgilbert** [comment]
@dustymabe To avoid accidents, could you update the checklist with the correct steps?

**Comment by dustymabe** [comment]
> @dustymabe To avoid accidents, could you update the checklist with the correct steps?

I opened a PR to handle this but in general my steps were:

- go to fcos config repo and pull all remote updates
- check out latest `testing` branch
- run `promote-config.sh next` from the `fedora-coreos-releng-automation` repo
- add another commit on top that switches the manifest.yaml to `35` and other bits
- open PR

**Comment by dustymabe** [comment]
- [promotion PR](https://github.com/coreos/fedora-coreos-config/pull/1326) - merge when ready next week

**Comment by gursewak1997** [comment]
Builds for testing release

- x86_64: https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/3215/
- aarch64: https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/multi-arch-pipeline/271/

**Comment by dustymabe** [comment]
> * aarch64: https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/multi-arch-pipeline/271/

This failed with 

```
[2021-11-09T01:09:19.723Z]     Updating metadata for 'updates-modular'...done
[2021-11-09T01:09:19.723Z]     error: Updating rpm-md repo 'updates-modular': cannot update repo 'updates-modular': Yum repo downloading error: Downloading error(s): repodata/2a2b3b2f2ec52734199a93e91f76fe6232764d5196afd56d19a7a92084b43b6f-filelists.xml.zck - Download failed: Curl error (23): Failed writing received data to disk/application for https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux//updates/35/Modular/aarch64/repodata/2a2b3b2f2ec52734199a93e91f76fe6232764d5196afd56d19a7a92084b43b6f-filelists.xml.zck [Failure writing output to destination]; Last error: Downloading successful, but checksum doesn't match. Calculated: 8964b7311b82531c512ec68de41186c02d8deb229b90eb92599175a2817aa9bf3c5ca8a78bfe231e0d182b0ac6b0655859ed2df96f4a45467b18f2f95fe9648f(sha512)  Expected: 140d98b7dd2a3468d35d21a6fcaa158fe05f36fd83aa564c81f0e8a1f6a1639e0378481c0be7829087302b055515fd5053caa0b691d50d8e04c5429af0057294(sha512)
```

I think this was an infra "flake" that happened because the updates-modular repos were getting updated at this exact time.

The test re-run succeeded. I'm going to kick off a new run and hopefully it will pass this time.

**Comment by dustymabe** [comment]
ahh I see it was actually [#270](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/multi-arch-pipeline/270/) that failed and 271 is the new job @gursewak1997 started.

**Comment by gursewak1997** [comment]
Release job: https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/931/parameters/

**Comment by gursewak1997** [comment]
Rollout PR: https://github.com/coreos/fedora-coreos-streams/pull/413

**Comment by gursewak1997** [comment]
Housekeeping: https://github.com/coreos/fedora-coreos-streams/issues/415
