### ISSUE TITLE
Add basic CI check for release notes YAML doc

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-streams#628]
We've hit syntax and schema errors multiple times in that file now. Would be good to have a basic check in place to catch this.

**Comment by marmijo** [comment]
This week, @aaradhak  and I discussed this CI check and the scope of the job.
 Just for reference, this would be beneficial in situations like these: https://github.com/coreos/fedora-coreos-streams/pull/918#discussion_r1657435288

**Comment by aaradhak** [comment]
I can use it fore reference for the CI check. Thanks!
