### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [coreos/fedora-coreos-streams#687]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by bgilbert** [comment]
Hey, thanks for reaching out.  The main issue tracker for Fedora CoreOS is [fedora-coreos-tracker](https://github.com/coreos/fedora-coreos-tracker/) and I've now enabled vulnerability reporting there.  Could you submit your report in that repo?

**Comment by bgilbert** [comment]
So far we haven't received a vulnerability report from you in the [fedora-coreos-tracker repo](https://github.com/coreos/fedora-coreos-tracker/).  I'll go ahead and close out this issue, but feel free to file your report over there.
